# Generated by Django 4.2 on 2023-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='for_device',
            field=models.ManyToManyField(to='commision.device'),
        ),
    ]
