# Generated by Django 4.2 on 2023-06-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0003_category_command_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='category',
            field=models.ForeignKey(default='Without Category', on_delete=django.db.models.deletion.DO_NOTHING, to='commision.category'),
        ),
    ]
