# Generated by Django 4.2 on 2023-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0005_rename_text_command_command_alter_command_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='check_exclude',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='command',
            name='check_include',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='command',
            name='out_line_limit',
            field=models.IntegerField(default=0),
        ),
    ]
