# Generated by Django 4.2 on 2023-06-23 13:40

import commision.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0006_command_check_exclude_command_check_include_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='check_exclude',
            field=commision.models.NonStrippingTextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='command',
            name='check_include',
            field=commision.models.NonStrippingTextField(blank=True, default='', max_length=1024),
        ),
    ]
