# Generated by Django 4.2 on 2023-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0007_alter_command_check_exclude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='check_exclude',
            new_name='false_if_include',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='check_include',
            new_name='ok_if_include',
        ),
    ]
