# Generated by Django 4.2 on 2023-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision', '0011_remove_command_false_if_include_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomicSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('region', models.CharField(max_length=128)),
                ('core_ip_list', models.CharField(max_length=1024)),
            ],
        ),
    ]
